/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riswanagam_191011400122_uas;


import Model.RiswanAgam_Customer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.Locale;


/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
public class RiswanAgam_BiodataFrame extends javax.swing.JFrame {

    /**
     * Creates new form RiswanAgam_BiodataFrame
     */
    RiswanAgam_Customer customer;
    public RiswanAgam_BiodataFrame(RiswanAgam_Customer customer) {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setBounds(width/2-200,height/2-250,490,430);
        setResizable(false);
        setTitle("Biodata");
        this.customer = customer;
        initText();  
    }
    /*
        Method untuk inisialisasi text
        pada frame biodata.
    */
    public void initText() {
        ID_label.setText("ID : "+customer.getId());
        nama_label.setText("Nama : \t"+customer.getNama());
        NIM_label.setText("NIM : \t"+customer.getNIM());
        no_tlp_label.setText("no tlp : \t"+customer.getNoTlp());
        pekerjaan_label.setText("Pekerjaan : \t"+customer.getPekerjaan());
        /*
            konfersi ke rupiah 
        */
        Locale locale = new Locale("id","ID");
        NumberFormat nf = NumberFormat.getCurrencyInstance(locale);
        total_uang_label.setText("Total Uang : \t"+nf.format(customer.getTotalUang()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama_label = new javax.swing.JLabel();
        NIM_label = new javax.swing.JLabel();
        no_tlp_label = new javax.swing.JLabel();
        pekerjaan_label = new javax.swing.JLabel();
        total_uang_label = new javax.swing.JLabel();
        ID_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Biodata");

        nama_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_label.setText("Nama : ");

        NIM_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NIM_label.setText("NIM :");

        no_tlp_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no_tlp_label.setText("no tlp :");

        pekerjaan_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pekerjaan_label.setText("Pekerjaan :");

        total_uang_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_uang_label.setText("Total Uang : ");

        ID_label.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ID_label.setText("ID :");

        back_btn.setText("Kembali");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIM_label)
                            .addComponent(nama_label)
                            .addComponent(no_tlp_label)
                            .addComponent(pekerjaan_label)
                            .addComponent(total_uang_label)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(back_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39)
                .addComponent(nama_label)
                .addGap(42, 42, 42)
                .addComponent(NIM_label)
                .addGap(42, 42, 42)
                .addComponent(pekerjaan_label)
                .addGap(42, 42, 42)
                .addComponent(no_tlp_label)
                .addGap(42, 42, 42)
                .addComponent(total_uang_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(back_btn)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
        Kembali ke main menu
    */
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_Mainmenu(customer).setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_label;
    private javax.swing.JLabel NIM_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama_label;
    private javax.swing.JLabel no_tlp_label;
    private javax.swing.JLabel pekerjaan_label;
    private javax.swing.JLabel total_uang_label;
    // End of variables declaration//GEN-END:variables

}
