/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riswanagam_191011400122_uas;


import Model.RiswanAgam_Customer;
import Model.RiswanAgam_Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;


/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
public class RiswanAgam_Mainmenu extends javax.swing.JFrame {
    private RiswanAgam_Customer customer;
    private RiswanAgam_Database database;
    /**
     * Creates new form RiswanAgam_mainMenu
     */
    public RiswanAgam_Mainmenu(RiswanAgam_Customer customer) {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setBounds(width/2-200,height/2-300,710,690);
        database = new RiswanAgam_Database();
        database.connection();
        this.customer = customer;
        nama_label.setText("Selamat datang, "+customer.getNama());
        setTitle("Menu Utama");
        setResizable(false);
        totalUangKas();
        play();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_panel = new javax.swing.JPanel();
        nama_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nama_tugas_label = new javax.swing.JLabel();
        Panel_2 = new javax.swing.JPanel();
        nama_aplikasi_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        total_uangKas = new javax.swing.JLabel();
        menuBar_mainMenu = new javax.swing.JMenuBar();
        menu_item_profile = new javax.swing.JMenu();
        profile_menuItem = new javax.swing.JMenuItem();
        user_tergabung = new javax.swing.JMenuItem();
        logout_menuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        transaksi_menuItem = new javax.swing.JMenuItem();
        history_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nama_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nama_label.setText("Selamat datang, Riswan Agam");

        nama_tugas_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nama_tugas_label.setText("Tugas UAS Pemrograman ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nama_tugas_label)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama_tugas_label)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        nama_aplikasi_label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        nama_aplikasi_label.setText("Aplikasi Uang Kas");
        nama_aplikasi_label.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nama_aplikasi_labelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout Panel_2Layout = new javax.swing.GroupLayout(Panel_2);
        Panel_2.setLayout(Panel_2Layout);
        Panel_2Layout.setHorizontalGroup(
            Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama_aplikasi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_2Layout.setVerticalGroup(
            Panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(nama_aplikasi_label)
                .addContainerGap())
        );

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unpam.png"))); // NOI18N

        total_uangKas.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        total_uangKas.setText("Total Uang Kas ");

        javax.swing.GroupLayout background_panelLayout = new javax.swing.GroupLayout(background_panel);
        background_panel.setLayout(background_panelLayout);
        background_panelLayout.setHorizontalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(logo_label)
                .addGap(0, 183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nama_label)
                .addGap(169, 169, 169))
            .addGroup(background_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(background_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(total_uangKas, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background_panelLayout.setVerticalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addComponent(logo_label)
                .addGap(33, 33, 33)
                .addComponent(nama_label)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(total_uangKas)
                .addGap(36, 36, 36))
        );

        menu_item_profile.setText("File");
        menu_item_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_profileActionPerformed(evt);
            }
        });

        profile_menuItem.setText("Profile");
        profile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_menuItemActionPerformed(evt);
            }
        });
        menu_item_profile.add(profile_menuItem);

        user_tergabung.setText("Lihat semua user");
        user_tergabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_tergabungActionPerformed(evt);
            }
        });
        menu_item_profile.add(user_tergabung);

        logout_menuItem.setText("Logout");
        logout_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuItemActionPerformed(evt);
            }
        });
        menu_item_profile.add(logout_menuItem);

        menuBar_mainMenu.add(menu_item_profile);

        jMenu1.setText("Menu");

        transaksi_menuItem.setText("Transaksi");
        transaksi_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(transaksi_menuItem);

        history_menuItem.setText("History");
        history_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(history_menuItem);

        menuBar_mainMenu.add(jMenu1);

        setJMenuBar(menuBar_mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void menu_item_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_profileActionPerformed
        // TODO add your handling code here:
        //new RiswanAgam_TransaksiFrame(customer).setVisible(true);

    }//GEN-LAST:event_menu_item_profileActionPerformed
    /*
        Open biodata / profile frame
    */
    private void profile_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_menuItemActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_BiodataFrame(customer).setVisible(true);
        dispose();
    }//GEN-LAST:event_profile_menuItemActionPerformed
     /*
        Open login frame
    */
    private void logout_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuItemActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_menuItemActionPerformed
     /*
        Open transaksi frame
    */
    private void transaksi_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_menuItemActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_TransaksiFrame(customer).setVisible(true);
        dispose();
    }//GEN-LAST:event_transaksi_menuItemActionPerformed
      /*
        Open history frame
    */
    private void history_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_menuItemActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_HistoryFrame().setVisible(true);
    }//GEN-LAST:event_history_menuItemActionPerformed
      /*
        Open ListTergabung frame
    */
    private void user_tergabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_tergabungActionPerformed
        // TODO add your handling code here:
       new RiswanAgam_ListTergabung().setVisible(true);
        
    }//GEN-LAST:event_user_tergabungActionPerformed

    private void nama_aplikasi_labelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nama_aplikasi_labelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_aplikasi_labelAncestorAdded
    /*
        Method yang digunakan untuk mengambil data seluruh
        uang kas pada database, dan dihitung totalnya
        lalu ditampilkan melalui variable total_uangKas.
    */
    private void totalUangKas() {
        try {
            ResultSet res = database.getResult(); 
            long totalUang = 0;
            PreparedStatement ps = database.getConn().prepareStatement("select SUM(uang_kas) as total_uang from penyimpanan");
            res = ps.executeQuery();
            if(res.next()) {
               // System.out.println(database.toString());
                totalUang = res.getLong("total_uang");
            }
            Locale locale = new Locale("id","ID");
            NumberFormat nf = NumberFormat.getCurrencyInstance(locale);
            total_uangKas.setText("Total Uang Kas "+nf.format(totalUang));
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_2;
    private javax.swing.JPanel background_panel;
    private javax.swing.JMenuItem history_menuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_label;
    private javax.swing.JMenuItem logout_menuItem;
    private javax.swing.JMenuBar menuBar_mainMenu;
    private javax.swing.JMenu menu_item_profile;
    private javax.swing.JLabel nama_aplikasi_label;
    private javax.swing.JLabel nama_label;
    private javax.swing.JLabel nama_tugas_label;
    private javax.swing.JMenuItem profile_menuItem;
    private javax.swing.JLabel total_uangKas;
    private javax.swing.JMenuItem transaksi_menuItem;
    private javax.swing.JMenuItem user_tergabung;
    // End of variables declaration//GEN-END:variables
    
    /*
        Animasi text 
    */
    private int dx = -60;
    public void play() {
        new Thread(() -> {
            while(true) {
                dx++;
                /*
                ketika posisi text sudah melebihi frame
                maka posisinya akan dimulai dari x = -180
                atau sebelum frame
                */
                if(dx > 780 ) dx = -180;
                try {
                    /*
                       delay waktu bergerak
                    */
                    Thread.sleep(15);
                } catch(Exception e) {e.printStackTrace();}
                /*
                    set lokasi pada text (label)
                */
                nama_aplikasi_label.setLocation(dx, 10);
            }
        }).start();
    }
}
