/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riswanagam_191011400122_uas;

import Model.RiswanAgam_Customer;
import Model.RiswanAgam_Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
public class RiswanAgam_TransaksiFrame extends javax.swing.JFrame {
    
    private final int SIMPAN_UANG = 1;
    private final int AMBIL_UANG = 2;
    private boolean AMBIL = false;

    private RiswanAgam_Database database; //  Database model
    private RiswanAgam_Customer customer; // Customer model
    /**
     * Creates new form RiswanAgam_penyimpananFrame
     * @param customer
     */
    public RiswanAgam_TransaksiFrame(RiswanAgam_Customer customer) {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setBounds(width/2,height/2-100,390,190);
        this.customer = customer;
        database = new RiswanAgam_Database();
        database.connection();
        setResizable(false);
        setTitle("Transaksi");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jumlahUang_input = new javax.swing.JTextField();
        simpan_btn = new javax.swing.JButton();
        ambil_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Jumlah Uang Rp.");

        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });

        ambil_btn.setText("Ambil");
        ambil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambil_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Menu");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jumlahUang_input, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(simpan_btn)
                                .addGap(18, 18, 18)
                                .addComponent(ambil_btn)
                                .addGap(41, 41, 41))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumlahUang_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_btn)
                    .addComponent(ambil_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_btn)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // ************************* ^_^  ^_^  ^_^ ********************************* \\

    private void transaksi(int tr) {
        long jumlahUangInput = Long.parseLong(jumlahUang_input.getText());
        long uangSaatIni = customer.getTotalUang();
        String keterangan = tr == SIMPAN_UANG ? "SIMPAN":"AMBIL";
        boolean updateData = false;
        switch(tr) {
            case SIMPAN_UANG:
                customer.setTotalUang( uangSaatIni + jumlahUangInput);
                updateData = true;
                break;
            case AMBIL_UANG :
                if(jumlahUangInput <= uangSaatIni) {
                     customer.setTotalUang( uangSaatIni - jumlahUangInput);
                     updateData = true;
                     AMBIL = true;
                } else {
                    JOptionPane.showMessageDialog(null,"Maaf uang anda tidak cukup.");
                    return;
                }
                break;
        }
        if(updateData) {
            try {
                //System.out.println(database.toString());
                /*
                    update kolom uang per user.
                    menggatikan uang yang lama dengan yang baru customer.getTotalUang()
                    setelah ditambah atau dikurang.
                */
                String updateTablePenyimpanan = "update penyimpanan set uang_kas=?"
                  +" where id_customer="+customer.getId()+";";
                PreparedStatement ps = database.getConn().prepareStatement(updateTablePenyimpanan);
                ps.setObject(1,customer.getTotalUang());
                ps.execute();
                /*
                    new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                    Mengambil format tahun-bulan-hari jam-menit-detik dalam bentuk string.
                */
                String timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                /*
                    masukan data kedalam table history
                */
               database.getStat().execute("insert into history(id_customer,waktu_history,jumlah_uang,keterangan_history)"
                       + " values("+customer.getId()+",'"+timestamp +"',"+Long.parseLong(jumlahUang_input.getText())+",'"
                       + keterangan+"');");
            } catch(SQLException e) {
                e.printStackTrace();
            }
        }
    }
    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        if(jumlahUang_input.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Masukan Uang");
            return;
        }
        transaksi(SIMPAN_UANG);
        JOptionPane.showMessageDialog(null,"Penyimpanan Sukses");
        new RiswanAgam_Mainmenu(customer).setVisible(true);
        dispose();
    }//GEN-LAST:event_simpan_btnActionPerformed

    private void ambil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambil_btnActionPerformed
        if(jumlahUang_input.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Masukan Uang");
            return;
        }
        transaksi(AMBIL_UANG);
        if(AMBIL) {
            JOptionPane.showMessageDialog(null,"Pengambilan Sukses");
            new RiswanAgam_Mainmenu(customer).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ambil_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_Mainmenu(customer).setVisible(true);
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambil_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jumlahUang_input;
    private javax.swing.JButton simpan_btn;
    // End of variables declaration//GEN-END:variables

   
}
