/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riswanagam_191011400122_uas;

import Model.RiswanAgam_Customer;
import Model.RiswanAgam_Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
public class RiswanAgam_LoginFrame extends javax.swing.JFrame {
    
    private RiswanAgam_Customer model_customer; // model class customer
    private RiswanAgam_Database database; // model class database
 
    /** 
     * Creates new form RiswanAgam_loginFrame
     */
    public RiswanAgam_LoginFrame() {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setBounds(width/2-200,height/2-250,410,224);
        database = new RiswanAgam_Database();
        database.connection();
        setTitle("Login");
        setResizable(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NIM_Input_textField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginPassword_textField = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        Registrasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Password");

        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        Registrasi.setText("Registrasi");
        Registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginPassword_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(login_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Registrasi))
                    .addComponent(NIM_Input_textField))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(NIM_Input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn)
                    .addComponent(Registrasi))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        try {
            database.setResult( database.getStat().executeQuery("select * from customers where NIM='"+NIM_Input_textField.getText()
                    +"';"));
            if(database.getResult().next()) {
                model_customer = new RiswanAgam_Customer();
//                setDataCustomer = new RiswanAgam_Database_helper();
                if(database.getResult().getString("password_customer").equals(loginPassword_textField.getText())) {
                    // Ambil ID dari table customers. 
                    int id = Integer.parseInt(database.getResult().getString("id_customer")); 
                    try {
                        /*
                            Masukan data ke dalam class model_customer
                            yang nanti datanya kita gunakan untuk profile.
                        */
                        model_customer.setId(id);
                        model_customer.setNIM(database.getResult().getString("NIM"));
                        model_customer.setNama(database.getResult().getString("nama_customer"));
                        model_customer.setNoTlp(database.getResult().getString("no_tlp_customer"));
                        model_customer.setPekerjaan(database.getResult().getString("pekerjaan"));
                         /*
                            Ambil total uang dari table penyimpanan pada database
                            yang memiliki relationship pada table customers.
                        */
                        database.setResult(database.getStat().executeQuery("select penyimpanan.uang_kas from "
                                + "penyimpanan inner join customers on penyimpanan.id_customer=customers.id_customer "
                                + "where penyimpanan.id_customer="+id+";"));
                        database.getResult().next();
                        model_customer.setTotalUang(database.getResult().getLong("uang_kas"));
                       
                    } catch(SQLException e) {
                        e.printStackTrace();
                    }
                       /*
                            Buka frame baru .
                        */
                        new RiswanAgam_Mainmenu(model_customer).setVisible(true);
                        dispose(); // close frame login.
                } else {
                    /*
                        Jika data tidak ada atau belum mendaftar.
                    */
                    JOptionPane.showMessageDialog(null,"Apakah anda sudah mendaftar ?\n"
                        + "Cek kembali NIM anda atau password anda.");
                }
            }
        }catch(SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void RegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrasiActionPerformed
        // TODO add your handling code here:
        /*
            Buka frame registrasi
        */
        RiswanAgam_RegisFrame frame = new RiswanAgam_RegisFrame();
        frame.setVisible(true);
        dispose(); //  close frame login
    }//GEN-LAST:event_RegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiswanAgam_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiswanAgam_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiswanAgam_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiswanAgam_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RiswanAgam_LoginFrame().setVisible(true);
            }
        });
    }
/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIM_Input_textField;
    private javax.swing.JButton Registrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField loginPassword_textField;
    private javax.swing.JButton login_btn;
    // End of variables declaration//GEN-END:variables

}