/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riswanagam_191011400122_uas;

import Model.RiswanAgam_Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Riswan Agam
 * @NIM 191011400122
 * @Tugas UAS
 */
public class RiswanAgam_RegisFrame extends javax.swing.JFrame {
    
    private RiswanAgam_Database database; // Database Model

    /**
     * Creates new form RiswanAgam_regisFrame
     */
    public RiswanAgam_RegisFrame() {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)size.getWidth();
        int height = (int)size.getHeight();
        setBounds(width/2-200,height/2-350,400,460);
        database = new RiswanAgam_Database();
        database.connection();
        setResizable(false);
        setTitle("Registrasi");
    }
    /*
        Method yang digunakan untuk cek semua field 
        untuk memastikan bahwa field sudah terisi atau belum.
    */
    public boolean isEmpty() {
        boolean field = no_tlp_input_textField.getText().equals("") 
                && password_input_textField.getText().equals("")
                && regis_nama_inputfield.getText().equals("")
                && NIM_input_textField.getText().equals("");
        if(field) JOptionPane.showMessageDialog(null,"Isi field kosong");
        return field;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regis_nama_inputfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        no_tlp_input_textField = new javax.swing.JTextField();
        submit_btn_regis = new javax.swing.JButton();
        clear_btn_regis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NIM_input_textField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pekerjaan_textField = new javax.swing.JTextField();
        password_input_textField = new javax.swing.JPasswordField();
        kembali_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Password");

        jLabel3.setText("No tlp");

        submit_btn_regis.setText("Simpan");
        submit_btn_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btn_regisActionPerformed(evt);
            }
        });

        clear_btn_regis.setText("Clear");
        clear_btn_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn_regisActionPerformed(evt);
            }
        });

        jLabel4.setText("Registrasi");

        jLabel5.setText("NIM");

        jLabel6.setText("Pekerjaan");

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel4)
                .addGap(0, 183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pekerjaan_textField)
                    .addComponent(NIM_input_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(regis_nama_inputfield)
                    .addComponent(no_tlp_input_textField)
                    .addComponent(password_input_textField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submit_btn_regis)
                        .addGap(28, 28, 28)
                        .addComponent(clear_btn_regis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembali_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regis_nama_inputfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIM_input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(pekerjaan_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_tlp_input_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_btn_regis)
                    .addComponent(clear_btn_regis)
                    .addComponent(kembali_btn))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* 
        submit button digunakan untuk memasukan semua hasil input
        ke dalam database.
    */
    private void submit_btn_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btn_regisActionPerformed
        // TODO add your handling code here:
        if(!isEmpty()) { /*
                cek field input sudah terisi atau belum.
            */
            try {
                /*
                    Proses memasukan data dari input ke dalam database 
                    khusunya untuk table customers
                    menggunakan keyword :
                    insert into nama_table (param1,param2,..,) values(param1,param2,..,).
                */
                database.getStat().execute("insert into customers(nama_customer,password_customer,no_tlp_customer,NIM,pekerjaan) values("
                +"'"+ regis_nama_inputfield.getText()+"',"
                +"'"+ password_input_textField.getText()+"',"
                +"'"+ no_tlp_input_textField.getText()+"',"
                +"'"+ NIM_input_textField.getText()+"',"
                +"'"+ pekerjaan_textField.getText()+"')");
                /*
                    Proses memasukan data dari input ke dalam database 
                    khusunya untuk table penyimpanan
                    menggunakan keyword :
                    insert into nama_table (param1,param2,..,) values(param1,param2,..,).
                */
                database.getStat().execute("insert into penyimpanan(id_customer,uang_kas) "
                        + "values((select id_customer from customers where NIM='"
                        + NIM_input_textField.getText()+"'),0)");
                JOptionPane.showMessageDialog(null,"Anda Berhasil Daftar");
                new RiswanAgam_LoginFrame().setVisible(true);
                dispose();
            } catch(SQLException e) {
                e.printStackTrace();
                switch(e.getErrorCode()) { 
                    /* 
                        error 1062 : Jika nim sudah terdaftar.
                        karena NIM berbentuk unique key maka NIM tidak bisa
                        sama.
                    */
                    case 1062:
                        JOptionPane.showMessageDialog(null,"NIM Sudah Digunakan !!");
                        break;
                }   
            }
        }
    }//GEN-LAST:event_submit_btn_regisActionPerformed
    /*
        clear button digunakan menghapus seluruh tulisan pada field input.
    */
    private void clear_btn_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn_regisActionPerformed
        clear();
    }//GEN-LAST:event_clear_btn_regisActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        new RiswanAgam_LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembali_btnActionPerformed
    /*
        clear() = Kosongkan semua tulisan pada field
        mengisinya dengan string kosong (setText("")).
    */
    void clear() {
        regis_nama_inputfield.setText("");
        password_input_textField.setText("");
        no_tlp_input_textField.setText("");
        NIM_input_textField.setText("");
        pekerjaan_textField.setText("");
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIM_input_textField;
    private javax.swing.JButton clear_btn_regis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTextField no_tlp_input_textField;
    private javax.swing.JPasswordField password_input_textField;
    private javax.swing.JTextField pekerjaan_textField;
    private javax.swing.JTextField regis_nama_inputfield;
    private javax.swing.JButton submit_btn_regis;
    // End of variables declaration//GEN-END:variables
}
